#!/usr/bin/python
# Fix map.yaml file generated by buildMap.launch

import sys
import yaml

# Open YAML file
print("Fixing " + sys.argv[1] + ".yaml ...")
stream = file("../worlds/maps/" + sys.argv[1] + ".yaml", "r")
docs = yaml.full_load(stream)
stream.close();

# Fix origin z
docs["origin"][2] = 0;

# From absolute to relative path
index = docs["image"].rfind("/")
if index != -1:
    docs["image"] = docs["image"][index+1:]

# Write to file
stream = file("../worlds/maps/" + sys.argv[1] + ".yaml", "w")
yaml.dump(docs, stream)
stream.close()

print("Done.")
